export const ekstolp = {
  dimensionsWithCosts: [
    {
      dimension: '50*50 mm',
      length: '1.7-1.9 m',
      pricePerUnit: 38,
      sharpeningCost: 6,
    },
    {
      dimension: '63*63 mm',
      length: '1.7-1.9 m',
      pricePerUnit: 65,
      sharpeningCost: 8,
    },
    {
      dimension: '75*75 mm',
      length: '1.7-1.9 m',
      pricePerUnit: 95,
      sharpeningCost: 12,
    },
  ],
  dimensionsWithPricePerLpm: [
    {
      dimension: '100*100 mm',
      pricePerLpm: 110,
    },
    {
      dimension: '125*125 mm',
      pricePerLpm: 129,
    },
    {
      dimension: '150*150 mm',
      pricePerLpm: 175,
    },
    {
      dimension: '175*175 mm',
      pricePerLpm: 220,
    },
    {
      dimension: '200*200 mm',
      pricePerLpm: 280,
    },
  ],
};

export const list = [
  {
    artikelnr: '7501',
    typ: 'Bastupanel Softline',
    dimension: '15*63',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '25',
    anmarkning: '',
  },
  {
    artikelnr: '7502',
    typ: 'Bastupanel Softline',
    dimension: '15*90',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '39',
    anmarkning: '',
  },
  {
    artikelnr: '7503',
    typ: 'Bastupanel Liggande',
    dimension: '16*83',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '37,5',
    anmarkning: '',
  },
  {
    artikelnr: '7504',
    typ: 'Bastupanel Faspanel',
    dimension: '15*63',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '25',
    anmarkning: '',
  },
  {
    artikelnr: '7505',
    typ: 'Bastupanel Natur',
    dimension: '15*95',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '29',
    anmarkning: 'Slutsåld',
  },
  {
    artikelnr: '7506',
    typ: 'Bastu Panel Exklusiv (Big Hill)',
    dimension: '21*95',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '62',
    anmarkning: '',
  },
  {
    artikelnr: '8001',
    typ: 'Bastulav',
    dimension: '22*63',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '39',
    anmarkning: '',
  },
  {
    artikelnr: '8002',
    typ: 'Bastulav',
    dimension: '22*90',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '65',
    anmarkning: '',
  },
  {
    artikelnr: '8003',
    typ: 'Bastulav',
    dimension: '22*45',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '32',
    anmarkning: '',
  },
  {
    artikelnr: '8004',
    typ: 'Bastulav',
    dimension: '22*63',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '39',
    anmarkning: '',
  },
  {
    artikelnr: '8005',
    typ: 'Bastulav',
    dimension: '22*120',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '78',
    anmarkning: '',
  },
  {
    artikelnr: '7509',
    typ: 'Taklist Antik',
    dimension: '22*65',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '45',
    anmarkning: '',
  },
  {
    artikelnr: '7510',
    typ: 'Taklist Antik (se bildark)',
    dimension: '22*65',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '55',
    anmarkning: '',
  },
  {
    artikelnr: '7511',
    typ: 'Taklist Antik',
    dimension: '22*65',
    traslag: 'Björk',
    enhet: 'Lpm',
    pris: '45',
    anmarkning: '',
  },
  {
    artikelnr: '7512',
    typ: 'Taklist Antik',
    dimension: '22*65',
    traslag: 'Fur',
    enhet: 'Lpm',
    pris: '32',
    anmarkning: '',
  },
  {
    artikelnr: '7513',
    typ: 'Taklist Funkis',
    dimension: '38*63',
    traslag: 'AL',
    enhet: 'Lpm',
    pris: '55',
    anmarkning: '',
  },
  {
    artikelnr: '7514',
    typ: 'Taklist Funkis',
    dimension: '38*63',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '65',
    anmarkning: '',
  },
  {
    artikelnr: '7515',
    typ: 'Taklist Funkis',
    dimension: '38*63',
    traslag: 'Björk',
    enhet: 'Lpm',
    pris: '55',
    anmarkning: '',
  },
  {
    artikelnr: '7516',
    typ: 'Taklist Funkis',
    dimension: '38*63',
    traslag: 'Fur',
    enhet: 'Lpm',
    pris: '42',
    anmarkning: '',
  },
  {
    artikelnr: '7601',
    typ: 'Foder/Slät',
    dimension: '12*63',
    traslag: 'EK',
    enhet: 'Lpm',
    pris: '37',
    anmarkning: '',
  },
  {
    artikelnr: '7602',
    typ: 'Golvlist/Slät',
    dimension: '12*63',
    traslag: 'EK',
    enhet: 'Lpm',
    pris: '37',
    anmarkning: '',
  },
  {
    artikelnr: '7603',
    typ: 'Foder/Slät',
    dimension: '14*90',
    traslag: 'EK',
    enhet: 'Lpm',
    pris: '65',
    anmarkning: '',
  },
  {
    artikelnr: '7604',
    typ: 'Golvlist/Slät',
    dimension: '14*90',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '65',
    anmarkning: '',
  },
  {
    artikelnr: '7605',
    typ: 'Planhyvlat',
    dimension: '21*70',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '45',
    anmarkning: '',
  },
  {
    artikelnr: '7606',
    typ: 'Planhyvlat',
    dimension: '21*90',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '70',
    anmarkning: '',
  },
  {
    artikelnr: '7607',
    typ: 'Planhyvlat',
    dimension: '21*120',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '85',
    anmarkning: '',
  },
  {
    artikelnr: '7607',
    typ: 'Taklist',
    dimension: '21*68',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '58',
    anmarkning: '',
  },
  {
    artikelnr: '7608',
    typ: 'Arkitekt panel (B-Sund)',
    dimension: '16*90',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '56',
    anmarkning: '',
  },
  {
    artikelnr: '7609',
    typ: 'Pärlspont Ek',
    dimension: '15*70',
    traslag: 'Ek',
    enhet: 'Kvm',
    pris: '750',
    anmarkning: '',
  },
  {
    artikelnr: '7630',
    typ: 'Slätpanel',
    dimension: '15*90',
    traslag: 'Ek',
    enhet: 'Lmp',
    pris: '39',
    anmarkning: '',
  },
  {
    artikelnr: '7610',
    typ: 'Trall',
    dimension: '22*95',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '37',
    anmarkning: '',
  },
  {
    artikelnr: '7611',
    typ: 'Trall',
    dimension: '22*120',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '48',
    anmarkning: '',
  },
  {
    artikelnr: '7612',
    typ: 'Trall',
    dimension: '28*120',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '62',
    anmarkning: '',
  },
  {
    artikelnr: '7613',
    typ: 'Trall',
    dimension: '28*145',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '89',
    anmarkning: '',
  },
  {
    artikelnr: '7701',
    typ: 'Ekpanel Utv',
    dimension: '22*120',
    traslag: 'Ek',
    enhet: 'Lpm',
    pris: '56',
    anmarkning: 'Valfriprofil',
  },
  {
    artikelnr: '7701',
    typ: 'Arkitektpanel Utv',
    dimension: '21*120',
    traslag: 'Asp',
    enhet: 'lpm',
    pris: '38',
    anmarkning: '',
  },
  {
    artikelnr: '7702',
    typ: 'Bastulav',
    dimension: '22*70',
    traslag: 'Asp',
    enhet: 'lpm',
    pris: '37',
    anmarkning: '',
  },
  {
    artikelnr: '7703',
    typ: 'Bastulav',
    dimension: '22*45',
    traslag: 'Asp',
    enhet: 'lpm',
    pris: '28',
    anmarkning: '',
  },
  {
    artikelnr: '7801',
    typ: 'Golvlist 1800-tal profil',
    dimension: '21*145',
    traslag: 'EK',
    enhet: 'lpm',
    pris: '145',
    anmarkning: '',
  },
  {
    artikelnr: '7802',
    typ: 'Golvlist 1800-tal',
    dimension: '21*145',
    traslag: 'Ask',
    enhet: 'lpm',
    pris: '110',
    anmarkning: '',
  },
  {
    artikelnr: '7803',
    typ: 'Golvlist 1800-tal',
    dimension: '21*145',
    traslag: 'Fur',
    enhet: 'lpm',
    pris: '65',
    anmarkning: '',
  },
  {
    artikelnr: '7804',
    typ: 'Foder 1800-tal',
    dimension: '21*120',
    traslag: 'Ek',
    enhet: 'lpm',
    pris: '110',
    anmarkning: '',
  },
  {
    artikelnr: '7805',
    typ: 'Foder 1800-tal',
    dimension: '21*120',
    traslag: 'Ask',
    enhet: 'lpm',
    pris: '105',
    anmarkning: '',
  },
  {
    artikelnr: '7806',
    typ: 'Foder 1800-tal',
    dimension: '21*120',
    traslag: 'Fur',
    enhet: 'lpm',
    pris: '65',
    anmarkning: '',
  },
];
